server: "hub-cloud.browserstack.com"

common_caps:
  "browserstack.user": "BROWSERSTACK_USERNAME"
  "browserstack.key": "BROWSERSTACK_ACCESS_KEY"
  "project": "First Cucumber Android Project"
  "build": "browserstack-build-1"
  "browserstack.debug": true
  "app" : "bs://<app-id>"

browser_caps:
  -
    "device": "Google Pixel 8 Pro"
    "os_version": "14.0"
    "name": "parallel_test_1"
  -
    "device": "Samsung Galaxy S22 Ultra"
    "os_version": "12.0"
    "name": "parallel_test_2"
