server: "hub-cloud.browserstack.com"

common_caps:
  "browserstack.user": "BROWSERSTACK_USERNAME"
  "browserstack.key": "BROWSERSTACK_ACCESS_KEY"
  "project": "First Cucumber Android Project"
  "build": "Cucumber Android"
  "browserstack.debug": true

browser_caps:
  -
    "device": "Google Pixel 3"
    "os_version": "9.0"
    "app": "bs://<app-id>"
    "name": "first_test"
